-- CreateEnum
CREATE TYPE "InquiryKind" AS ENUM ('NEW_DEVELOPMENT', 'FEATURE_MODIFICATION', 'ISSUE_RESOLUTION');

-- AlterTable
ALTER TABLE "Inquiry"
ADD COLUMN "inquiryKind" "InquiryKind" NOT NULL DEFAULT 'NEW_DEVELOPMENT';
